compiler:
    solc:
        version: null
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3"

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.3


reports:
    exclude_contracts:
        - "ERC721"
        - "ERC721Pausable"
        - "ERC20PresetMinterPauser"
        - "ERC20Pausable"
        - "ERC20"
        - "AccessControl"
        - "Address"
        - "ERC721Enumerable"
        - "ERC721URIStorage"
        - "SafeERC20"
        - "Initializable"
        - "ReentrancyGuard"
        - "IERC20"
        - "IERC721"
        - "Math"
        - "Ownable"
        - "Strings"
